### ISSUE TITLE
Persons + Organisations (Names) Repository Integration / API (AgentSet and others)

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#107]
**For detailed specifications, please refer to: [Google Doc: "Persons + Organisations Service"] (https://docs.google.com/document/d/11SUU6h9jMZBJ-2aB61us3WKiiY2Ab22njJEl_zF9z-M/edit#heading=h.h7gghh7nqmzm)**

Architecture:
![repositories schema](https://f.cloud.github.com/assets/3493493/1079954/8fdc52be-1556-11e3-948f-9eb82884bc26.png)

**Comment by MatthiasArnold** [comment]
implementation of local viaf mirror is not of priority anymore. needs to be approached with an offline ziziphus (in connection with "tamboti-to-go") in the future.
viaf is queried live using the api.
