### ISSUE TITLE
DateSet: styling issues (EDIT Mode)

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#146]
*Please note, that all suggestions for the styling of the dateSet within this ticket are equally relevant for both, earliestDate as well as latestDate - even if the examples are demonstrated in only one of these cases!*

Another example: #153 

Status Quo:
![03-02-2014 14-32-44](https://f.cloud.github.com/assets/3493493/2065201/1d6532a6-8cdd-11e3-8d5c-3f14dd7d9d4b.png)

***1)***
Label and checkbox for circa="true"/"false" must be recognizable as belonging together (if shown at all, please read below under 2)
Also @type and the pulldown-menu for date values (etc.) should appear as a couple
(see mockup below!)

***2)***
*circa & type values*
"Grey out" label "circa" and the checkbox for circa-value (whether checked or not).
The Checkbox for "circa" value should NOT be editable but set to "checked" (circa="true"), whenever one of the values from the types pulldown-menu is being chosen (ref. issue #) in order to give a more precise definition of what "circa" is.

***3)***
Hide the complete AlternativeNotation-Section from the Edit-field, apart from the "ADD" button labelled "Add [AlternativeNotation]".

***4)***
Add labels to differentiate earliestDate and latestDate from each other.

NEW Mockup suggestion:
![03-02-2014 15-12-26](https://f.cloud.github.com/assets/3493493/2065932/76ca661c-8ce8-11e3-8fa2-6c78e8659e90.png)

see also #147

**Comment by MatthiasArnold** [comment]
works
