### ISSUE TITLE
Integrate user feedback communication into Ziziphus

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#160]
A simple user feedback system should be part of Ziziphus, ideally in the form of a Feedback-button / bookmarklet as an INTERGATED PART of the database's front-end:

![02-04-2014 12-31-27](https://cloud.githubusercontent.com/assets/3493493/2589933/2dc12aa2-ba54-11e3-8417-57634433cf78.png)

In a new window, it should offer various options for users to talk about their experience:
"Error" 
"Question", 
"New function/ idea" 
(...)
could be categories to be preselectable by the user. Those categories should be immediately understandable by common users (not necessarily tech-savvy!) and be kept in simple common sense language. 
PLUS: a free text field with unlimited space to explain what was going on.

**back-end**
Ideally those comments directly feed into a tracking system like github in the backend where they can be easily managed collaboratively by admin staff. Admins watching the repository will be emailed in any case as soon as a new ticket has been created and can then "clean up".
Also, those user-generated tickets should feed into a special category within this tracking system (this could be a specific *label* such as *"user feedback"*). 

**bonding**
The effort of a user's help should be appreciated and valued as much as possible:
In ANY case, there should be a notification (after submitting), that the individual feedback has been recognized and saved, with a "thank you".

Additionally a user could be redirected to the new ticket or provided with a link into the (public) tracking system together with a text explaining where the overall development of the System in relation to a user's development commitment can be tracked.

Feedback should by default be "anonymous" feedback, but as users are logged in in most cases, there could also be an option for users to be notified when the problem has been worked on or solved as long as this is still feasible without too much administrative effort for staff.

**Comment by jodevelops** [comment]
close? 
Core functionality is there, except for "happy extra" features.

**Comment by jodevelops** [comment]
the feature does not work at the moment:
please see https://github.com/betterFORM/ziziphus/issues/277

Alternative notion:
WHY NOT sending an email directly to "ziziphus@kjc.uni-heidelberg.de" with the text from the "report an issue field". We should still think about offering an option for users to give feedback directly from within the system.

@ChiSamurai: how much effort would that be to set up?
I am thinking about previous comments from lars @windauer :

> Due to disabled "Cross Origin Resource Sharing" (CORS) on the Redmine server we can't give the user feedback if the ticket was created or not (cause our script does not know this either).

To implement feedback for the ticket creators this must be fixed first (see http://enable-cors.org/index.html to enable CORS)

**Comment by MatthiasArnold** [comment]
currently, the function produces an error message: 
"there was an error saving your feedback"

![image](https://cloud.githubusercontent.com/assets/3436613/8077291/c9831102-0f54-11e5-88da-87b669468228.png)

**Comment by zwobit** [comment]
done, uses l. credential for the 0.42 test build, will switch to new user for next build
