### ISSUE TITLE
some values come as NUMBERS in agent's controlled list

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#168]
Why are there some values not resolved? Search seems to work anyway, but the display shows the id, such as 30067498, instead of "Taj Mahal" (fictive example). See screenshot below.

i am in firefox

It happens here:
http://kjc-ws2.kjc.uni-heidelberg.de:8650/exist/apps/ziziphus/GroupEditor.xql

as well as here:
http://kjc-ws2.kjc.uni-heidelberg.de:8650/exist/apps/ziziphus/record.html?id=w_5833e459-08e0-54cf-b71a-45eeeb01211a&workdir=/db/resources/commons/Priya_Paul_Collection/

etc.

![18-06-2014 16-06-51](https://cloud.githubusercontent.com/assets/3493493/3314534/011bb424-f6f2-11e3-8418-962e7ad072f8.png)

**Comment by jodevelops** [comment]
the relation to changes within the tei generation is described here: http://kjc-sv013.kjc.uni-heidelberg.de/redmine/issues/767

**Comment by zwobit** [comment]
Maybe we could just delete the wrong entries from organisations_tei and rely on viaf lookup

**Comment by ChiSamurai** [comment]
Should be fixed now. Please check the relevant entries. If ok, ticket can be closed.

**Comment by jodevelops** [comment]
fine, checked with "Linden-Museum", "Roman Catholic Church" and other terms from organisations_tei
