### ISSUE TITLE
Subject: have info-hover show AAT bracket distinction (not just translations)

### ISSUE THREAD

**Issue by TonyBuchwald** [exc-asia-and-europe/ziziphus#193]
Using version 0.33.0 (after recent update) on sv016:

When adding subjects with several entries in AAT (e. g. "workshops"), hovering over the info symbol should offer AAT's bracketed distinctions rather than / in addition to the translations.
What I'm talking about:
![24-07-_2014_12-00-26](https://cloud.githubusercontent.com/assets/6152085/3686737/53535846-131c-11e4-9a72-61f470b9c923.jpg)
![ziziphus_33_subject-distinction_03](https://cloud.githubusercontent.com/assets/6152085/3686741/5c1b2904-131c-11e4-8005-b66359c8a876.jpg)
![ziziphus_33_subject-distinction_01](https://cloud.githubusercontent.com/assets/6152085/3686743/60140404-131c-11e4-9c48-ea06aea58c95.jpg)

I would suggest either:
![ziziphus_33_subject-distinction_02_suggestion](https://cloud.githubusercontent.com/assets/6152085/3686752/6f2c1378-131c-11e4-88f7-39aba86cca1d.jpg)
or:
![ziziphus_33_subject-distinction_03_suggestion](https://cloud.githubusercontent.com/assets/6152085/3686756/74db3eca-131c-11e4-91ed-3def20080878.jpg)

**Comment by jodevelops** [comment]
the choices from searches are displayed as detailed as described above now, close....
