### ISSUE TITLE
[agent] enhancement of automatic agent name-type 

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#228]
Currently, when a new agent name is added, the system chooses the name type via the cluster's subject type (such as "personal", or "corporate"  - see screenshot example) and will paste this value.

screenshot "status quo"
![05-11-2014 15-15-21](https://cloud.githubusercontent.com/assets/3493493/4919027/9ecea556-64f6-11e4-9dd6-ebc87553b722.png)

The dialogue should be enhanced, such as proposed below:
Desirable content of dialogue with an option to prevent further alerts:

"Ziziphus detected {CORPORATE} as a matching name type for {BAYER AG}. Set name type?
[OK] [No] [ ] remember this desicion for the rest of the session."

**Comment by MatthiasArnold** [comment]
Do we really need this additional dialog?

**Comment by MatthiasArnold** [comment]
dialog does not show anymore. good.
