### ISSUE TITLE
[display] show WORK record's thumbnail in image record

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#256]
There is a wrong thumbnail displayed in relationSet image record section (see screenshot).
It should correspond to the work record, that is associated with the image-reocord 
(types: ImageIs -- ImageOf).

!!- The correct relid (of the corresponding work record w_[...]) is loaded, but the display shows another thumbnail. 

- It is the same thumbnail across collection borders.

Status quo (ws2)
![09-12-2014 15-45-29](https://cloud.githubusercontent.com/assets/3493493/5359029/9652e930-7fba-11e4-9484-b135990f2c1d.png)

**Comment by MatthiasArnold** [comment]
cf. #260

**Comment by jodevelops** [comment]
close? / test?
