### ISSUE TITLE
"report an issue" button doesn't work

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#277]
there is an error message, when giving feedback from within Ziziphus via the "report an issue" button it should become a redmine-ticket, instead, there is an error message reading:

"There was an error saving your feedback. Please contact "ziziphus@kjc.uni-heidelberg.de"

![18-02-2015 16-10-53](https://cloud.githubusercontent.com/assets/3493493/6251646/653fec90-b795-11e4-8d1a-0b0542efd43a.png)

see also:
http://kjc-sv013.kjc.uni-heidelberg.de/redmine/issues/800

**Comment by MatthiasArnold** [comment]
update: the error message now pops up at a different location and within a (more or less) nice alert box. 
but the problem is still there...

**Comment by jodevelops** [comment]
now it says "Feedback saved successful!" - just where does it go to?
