### ISSUE TITLE
DateSet broken

### ISSUE THREAD

**Issue by SimonGruening** [exc-asia-and-europe/ziziphus#281]
The earliest Date free text field is missing.
![date-bug_2015](https://cloud.githubusercontent.com/assets/3437957/6393927/4cb2519c-bdce-11e4-92d3-f7382817e48e.png)

And it would be great, if we had "earliest Date" and "latest Date" as labels back again. :)

**Comment by zwobit** [comment]
input is back.

As for the label @SimonGruening  is the lang_en.xml file the current one? We have to change the label there, it says just "Date" right now for both Dates

**Comment by zwobit** [comment]
Close?

**Comment by SimonGruening** [comment]
Nope, can't be closed yet. The bin to delete DateSets is still missing.

**Comment by SimonGruening** [comment]
And there still seems to be a problem with the AlternativeNotation area. First it only appeared in the upper DateSet, now it appears only in the lower DateSet.
![image](https://cloud.githubusercontent.com/assets/3437957/6898307/b8c81d96-d6f9-11e4-9480-21fa21f82f2c.png)

**Comment by zwobit** [comment]
-- snip
And there still seems to be a problem with the AlternativeNotation area. First it only appeared in the upper DateSet, now it appears only in the lower DateSet.
-- snap

FYI: This is because there is no "AlternativeNotation" in the Data, for a new "Date" the template is copied which contains "AlternativeNotation"s, so they show up in the second row. What is missing though  are the Buttons to add or delete an "AlternativeNotation"

**Comment by zwobit** [comment]
Close? :)

**Comment by SimonGruening** [comment]
I still find it highly disturbing that I get Alternative Notations when I am adding a 2nd date. I guess as a user unfamiliar with Ziziphus I would find it even more disturbing.
And I don't quite understand what you mean, when you say "...for a new 'Date' the template is copied..." Which template? Is this the template of the first date added? If so, there shouldn't be an alternative notation as I didn't add one for the first date.

![2015-05-20_dateset](https://cloud.githubusercontent.com/assets/3437957/7729277/3671958c-ff14-11e4-934b-beb5dda5b4c7.PNG)
![2015-05-20_dateset_add_2nd_date](https://cloud.githubusercontent.com/assets/3437957/7729278/36773a5a-ff14-11e4-8505-6c2d25419333.PNG)

**Comment by MatthiasArnold** [comment]
currently (v0.41) the labels for "Add Alternative Notation" are missing completely (red markers).
within the alternative notation, the add/remove button also has no label showing (yellow marker).

![image](https://cloud.githubusercontent.com/assets/3436613/7838552/b58402dc-048d-11e5-8390-b4c1ac19819b.png)

**Comment by zwobit** [comment]
done

**Comment by MatthiasArnold** [comment]
works. 
though we will need validation of user input soon, to get valid xml (separate ticket).
