### ISSUE TITLE
[Material] Type Dropdown resets

### ISSUE THREAD

**Issue by SimonGruening** [exc-asia-and-europe/ziziphus#282]
When you choose the type from the drop-down first and thereafter start typing and choose a term, the type drop-down resets itself.

**Comment by zwobit** [comment]
Mmh, can not reproduce the error. Could you specify your work flow a little more?

**Comment by SimonGruening** [comment]
Unfortunately I clicked the wrong lable. It's the MaterialSet in which this occurs.

**Comment by zwobit** [comment]
At the moment Type is set to "materials" (in the background) if you use a value from the service. As "materials" is missing in the drop-down as value it is shown as "empty". 

Should we set a type here at all and if so which one?

**Comment by MatthiasArnold** [comment]
I'm not sure I understand why a type value in the background needs to be set. but should NOT overwrite the actual `@type`value added by the user. 

`<material> @type` is controlled by VRA Core 4.
possible values are: 
* medium
* support
* other

**Comment by zwobit** [comment]
type is not set any longer.
