### ISSUE TITLE
Pref-Box missing in TechniqueSet

### ISSUE THREAD

**Issue by SimonGruening** [exc-asia-and-europe/ziziphus#286]
Somehow the preference tick-box got lost in the TechniqueSet.
![image](https://cloud.githubusercontent.com/assets/3437957/7494304/17ee66fc-f407-11e4-9d73-8ca22c717e76.png)

**Comment by zwobit** [comment]
I think this intentional see https://github.com/exc-asia-and-europe/ziziphus/issues/49 comment number 10 from @ jodevelops (11 Sep 2013)

**Comment by MatthiasArnold** [comment]
no, i think this is a misunderstanding. the pref box should be there. only the validation is not needed, i.e. user may ignore it. but if users want, the can set a pref element.

**Comment by zwobit** [comment]
Note: Merge-style-sheet

**Comment by zwobit** [comment]
What about SubjectSet ? At the moment "pref" is also removed there

**Comment by MatthiasArnold** [comment]
the pref boxes should be available in subjectSet as well.
