### ISSUE TITLE
Controlled vocabularies: Enter selects first hit

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#289]
If a user searches for something in a controlled vocabulary (e.g. agent, or subject) and hits <ENTER>, the **first vocabulary term** should be written into the record. 
At the moment, <ENTER> selects the line "? Add new entry" - a function not yet implemented (triggers an error message).

This is especially relevant if one searches for an ID where exact (the right) one record should be found, e.g. "7001535" for Delhi in TGN.

**Comment by zwobit** [comment]
Moved: https://github.com/exc-asia-and-europe/rosids-shared/issues/3
