### ISSUE TITLE
"Add new entry" shows hidden icon

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#290]
when one hovers on the "i" button after the "? Add new entry" a hidden button becomes visible.

![22-05-2015 12-37-49](https://cloud.githubusercontent.com/assets/3436613/7769092/993709ea-0081-11e5-9944-1ca9d0ff7843.png)

**Comment by zwobit** [comment]
That is the info area without text, need to hide it when no additional info is present. Moved ticket to rosids-shared https://github.com/exc-asia-and-europe/rosids-shared/issues/2
