### ISSUE TITLE
TGN lookup needs more information

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#297]
To be able to make the right decision, which of the locations from TGN to choose, users will need more information in the result list. 

in addition to the placeName we also need (using "Heidelberg" as example):
* parentString (Baden-Württemberg, Deutschland, Europe, World)
* placeType (inhabited place)

Example: 
Heidelberg (inhabited place)
TGN: 7005177 (World, Europe, Germany, Baden-Württemberg) 

The output should be quite similar to a search result on the Getty TGN homepage:
https://www.getty.edu/vow/TGNServlet?english=Y&find=heidelberg&place=&page=1&nation=

**Comment by zwobit** [comment]
done

**Comment by MatthiasArnold** [comment]
works
