### ISSUE TITLE
controlled vocabularies: integrate local with external terms

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#298]
Local terms in controlled lists, that are mapped to external vocabularies, should not appear as separate hits, but be merged together.

**Example 1 - Agent:**
after entering "marx" as search term, the local term "Marx, Karl" [uuid-4682026c-37cd-59e6-8d1a-e03149aa51ff] is found. it SEEMS to be correct, pointing to the VIAF record, and even the viaf data is shown by the "i" field. However, only the local record gets linked.
![28-05-2015 15-13-58](https://cloud.githubusercontent.com/assets/3436613/7860793/621c099a-054c-11e5-9be1-821a998519bb.png)
![28-05-2015 15-14-10](https://cloud.githubusercontent.com/assets/3436613/7860795/6fa2cff4-054c-11e5-993f-76dc82e5968d.png)

instead, the local and the VIAF records should be ONE SINGLE hit.
![28-05-2015 15-05-10](https://cloud.githubusercontent.com/assets/3436613/7861082/550e7c72-054e-11e5-8caf-89b301eeac18.png)

**Example 2 - Subject:**
searching for newspapers retrieves two hits, the local "newspapers", and the AAT "newspapers" (#300026656). 
![28-05-2015 15-23-32](https://cloud.githubusercontent.com/assets/3436613/7861265/64c89048-054f-11e5-8561-c817fded07b0.png)

Since the local term is also mapped to the AAT term, they should be displayed as ONE SINGLE hit/record. 
![28-05-2015 15-23-32_changed](https://cloud.githubusercontent.com/assets/3436613/7861255/539dd670-054f-11e5-9a2c-2288a2f74d66.png)

**Comment by zwobit** [comment]
done for subjects + aat

**Comment by zwobit** [comment]
done local + viaf show as one hit

**Comment by zwobit** [comment]
should we link both ids? Or just one, then which one?

**Comment by MatthiasArnold** [comment]
we use the local records only to add certain information not available elsewhere. these should be found by the search.
but the id should point to the external authority file. 
once we have editors for the local authority files, we can add a link there as well.

**Comment by zwobit** [comment]
add getty icon, show aat info first in tooltip, then local informations

**Comment by zwobit** [comment]
done

**Comment by MatthiasArnold** [comment]
in Agent Names the ```@vocab``` value "VIAF" should be used, if available. 

For example, Karl Marx is available in both, local and VIAF repos. The attributes should **both point to the VIAF values**.
![18-08-2015 14-59-16](https://cloud.githubusercontent.com/assets/3436613/9330451/bfbd0416-45b9-11e5-8024-a75187077a2a.png)
___________________

in the Subjects example given above, now the AAT term "newspapers" (#300026656) is **missing completely**, only the local term stayed. did something change in the api query?
![18-08-2015 15-04-15](https://cloud.githubusercontent.com/assets/3436613/9330622/c511d288-45ba-11e5-9cf8-9d606ed16836.png)

**Comment by zwobit** [comment]
should be fixed

**Comment by jodevelops** [comment]
i looked at that, subjects are still being attribute="local", although there is an external authority file (such as aat). This is DIFFERENT from what we do in agent, where the local/viaf/(...) merged terms are attributed to viaf. 
-
Should we change that for subjects as well?

**Comment by zwobit** [comment]
done
