### ISSUE TITLE
[Location]-[Name]: allow VIAF

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#300]
In `<location><name>` we need to be able to search VIAF names as well, besides TGN. 
this is because many corporate terms (körperschaften, e.g. museums) are controlled there, and are not part of TGN.

**Comment by zwobit** [comment]
VIAF search done. Can/Should we somehow "filter" the VIAF search e.g. for organizations only?

**Comment by MatthiasArnold** [comment]
we can try using only the "corporate names", if possible?

**Comment by SimonGruening** [comment]
Wouldn't it make sense to also get "geographic names" from VIAF? I don't know how big the overlap between VIAF and TGN is with these, though.

**Comment by zwobit** [comment]
tooltip + open in viaf is still missing.

**Comment by zwobit** [comment]
done

**Comment by jodevelops** [comment]
looks good
