### ISSUE TITLE
[Location]: Name @type must be valid

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#301]
if in `<location><name @type>` the user does not select one of the values from the drop-down, a "`type="locations"`" is written into the record. this is not valid. 

valid entries are 
* corporate
* geographic
* personal
* other

if no value gets selected, the @type attribute should NOT be written in the xml.

![29-05-2015 14-59-34](https://cloud.githubusercontent.com/assets/3436613/7883026/8daba936-0613-11e5-8dc6-d4103c75e6f4.png)

![29-05-2015 14-59-56](https://cloud.githubusercontent.com/assets/3436613/7883029/93e8ba28-0613-11e5-9f87-a346c4b9fce6.png)

**enhancement:**
add a validation that checks if a type was chosen. if not, an alert "Please select the type of this location's name from the list." is shown and the record not saved.

**Comment by zwobit** [comment]
done
