### ISSUE TITLE
Add links to forms for "Add new entry" (controlled vocabs)

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#306]
The "Add new entry" link should point to these request forms (instead of displaying the "To be implemented..." alert):

agents:
https://docs.google.com/forms/d/1cMW6NS5bwgB3sB82hvUGnrp0nJR2Hr9dZuPmFvI6-y8/viewform

locations:
https://docs.google.com/forms/d/1X44GZ4Lk0WfO6Vp1M2UnOmiZF3V7tabLH39bj12YSKU/viewform

subjects:
https://docs.google.com/forms/d/111b2k3IQeVuJhk0NXsgdsokw-wexk5BjKmcJLF5jVeE/viewform

**Comment by zwobit** [comment]
done
