### ISSUE TITLE
Duration of browser session

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#308]
at the moment, the browser session is very short, less than 5 minutes. afterwards the user gets an "Your session expired. Please reload." alert and is forced to reload the page. can the duration of the session be extended?

**Comment by zwobit** [comment]
Increasing "maxIdleTime" in tools/jetty/etc/jetty.xml should help

**Comment by zwobit** [comment]
Or via tamboti/modules/search/check-session.xql like in tamboti

**Comment by zwobit** [comment]
Adopted mechanism from tamboti, should be 8H

**Comment by jodevelops** [comment]
the mechanism seems to be working
