### ISSUE TITLE
[Agent] hide agent-date "ca" checkboxes

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#313]
Since we use the types for uncertain `<agent><dates><earliestDate / latestDate>` the "ca." checkbox can be hidden. The value of @ca will still be set in the xml. 

![15-06-2015 12-24-47](https://cloud.githubusercontent.com/assets/3436613/8158209/48f474f8-135b-11e5-857b-d0e6703b0d25.png)

Also, the @type drop-downs should be positioned further left, closer to the respective date elements.

![15-06-2015 12-33-44](https://cloud.githubusercontent.com/assets/3436613/8158193/1fa5d6c8-135b-11e5-81ce-fc942b6406d2.png)

**Comment by jodevelops** [comment]
done?
