### ISSUE TITLE
[Agent] label for exact search missing

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#315]
the checkbox to perform an "exact search" within the name authority does not show its label, although it has been set in lang_en.xml.
![15-06-2015 13-33-38](https://cloud.githubusercontent.com/assets/3436613/8159078/b96efd22-1363-11e5-8b7b-e1ca05f31cf5.png)

**Comment by zwobit** [comment]
We need some mechanism to i18nify html controls. See also #316

**Comment by MatthiasArnold** [comment]
probably also related #281

**Comment by zwobit** [comment]
close?
