### ISSUE TITLE
[lang-en] add/remove alternativeNotation

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#320]
Entries for the labels of "Add Alternative Notation" and "Remove Alternative Notation" buttons are missing in the current lang_en.xml file. where should they be added? in the actions? or within dateSet?

**Comment by zwobit** [comment]
mmh, they should be in the action-segment, seems we lost them somehow. I will check the history of the lang-files.

**Comment by zwobit** [comment]
Seems they got lost here https://github.com/exc-asia-and-europe/ziziphus/commit/af1e2abfba78ac64d4575d8fca0f22771628caea

**Comment by zwobit** [comment]
cf #281

**Comment by MatthiasArnold** [comment]
yes, that explains #281. we have use local copies of lang_en.xml, which probably is why some changes were eliminated while content was expanded. will add these back in and send you our local one to upload into git. just make a diff before that.

we will stop working with local copies and only make changes on git.

**Comment by zwobit** [comment]
Close?
