### ISSUE TITLE
[feedback] change mail address for error alert

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#330]
in image https://cloud.githubusercontent.com/assets/3436613/8077291/c9831102-0f54-11e5-88da-87b669468228.png (cf. https://github.com/exc-asia-and-europe/ziziphus/issues/160) an error message can be seen in case something goes wrong with submitting feedback.
this mail address (ziziphus@kjc.uni-heidelberg.de) is not functional.

please change to the functional address: ziziphus@asia-europe.uni-heidelberg.de

**Comment by zwobit** [comment]
done
