### ISSUE TITLE
group editor: small image versions

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#333]
when opening a group of 2 (+) images in group view mode, only the FIRST is displayed in the expected size, all the others are displayed in a SMALLER version (scaled down).

**Comment by zwobit** [comment]
mmh, could not reproduce with ppcol + firefox

**Comment by jodevelops** [comment]
set to "low", apparently it's the image(s) itself that were unexpectedly small

**Comment by jodevelops** [comment]
will test as soon as the group viewer is on ws2
