### ISSUE TITLE
relation href "d1" ?

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#334]
i am looking at relations in
w_49b99fe6-1ea4-4163-b188-0c72852d92e4

the href of relation in position nr. 1 points towards this mods record:
http://kjc-ws2.kjc.uni-heidelberg.de:8650/exist/apps/tamboti/modules/search/index.html?search-field=ID&value=uuid-44f6400d-3b90-4206-bdc0-6076ce514318

**but its relation type="relatedTo" says "d1" as its relId value, where does that come from?**

![16-09-2015 14-13-10](https://cloud.githubusercontent.com/assets/3493493/9904459/26f9666c-5c7e-11e5-9ad1-a9bc1d2d9b23.png)

**Comment by zwobit** [comment]
Could you share the record with zak.patel?
