### ISSUE TITLE
relationSet: "imageIs" rel source = tamboti ?

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#335]
why, when the Image-Relation is set in a work / image record, it says "tamboti" as its "Source" value?
was that defined earlier somewhere else?

![16-09-2015 14-31-53](https://cloud.githubusercontent.com/assets/3493493/9904665/cff31e60-5c7f-11e5-95ce-2c3c37ce6580.png)

**Comment by zwobit** [comment]
Is this a record created by tamboti?

**Comment by zwobit** [comment]
This come from the Tamboti VRA-Generator (Upload):

https://github.com/exc-asia-and-europe/tamboti/blob/master/modules/upload/upload.xq#L26

**Comment by jodevelops** [comment]
if we want to change this, report here:
http://kjc-sv013.kjc.uni-heidelberg.de/redmine/projects/tamboti-support
