### ISSUE TITLE
[Agent] - saving of VIAF data not working

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#337]
in v.0.42, agentSet.

when one SEARCHES and chooses a name from the VIAF list, additional information, like agent-type, and dates are not automatically filled anymore. only the name is inserted (and dataDate set). after saving the data does NOT get saved but is lost. Only the dataDate value is saved in the record.

when the VIAF ID is used, data is pulled and stored correctly.

**Comment by zwobit** [comment]
Could you tell me what you searched? "karl  marx" and then choosing "Lenin" or "Marx" seems to work

**Comment by MatthiasArnold** [comment]
it seems to work again. 

i worked with this record:
http://kjc-ws2.kjc.uni-heidelberg.de:8650/exist/apps/tamboti/modules/search/index.html?search-field=ID&value=w_93ebc0ec-e063-4d76-a833-780b5ae64c94
but even the george grosz data is now there - very strange. perhaps the update of the form display had a hick-up?

**Comment by zwobit** [comment]
could you share it with zak.patel? Tamboti doesn´t show the record for me.

**Comment by MatthiasArnold** [comment]
hm. the collection is shared with zak patel, when i log in as zp it does work. can you please try again?

**Comment by zwobit** [comment]
mmh i always get "No records found."

**Comment by zwobit** [comment]
viaf , viaf + local seems to work. but local only fails

**Comment by zwobit** [comment]
done

**Comment by jodevelops** [comment]
tested for local Agent Names=
Angelika Hanke (uuid-fa735219-8181-4eb6-995a-9f8335c0bfd2)
Peter Blastenbrei (uuid-42625d57-bbcf-44fb-a6d2-58ff46541ec6)
result: saveable
