### ISSUE TITLE
[lang] - switching languages auto-fills all forms

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#339]
when one switches between languages, ALL elementSet forms will be auto-filled with the data from whichever elementSet was opened when the language switch was triggered. 

fortunately, data is not written to the record. ;)

![image](https://cloud.githubusercontent.com/assets/3436613/9939325/fd40974a-5d69-11e5-9e27-9a9b83ba282c.png)

**Comment by zwobit** [comment]
Should be fixed.

**Comment by MatthiasArnold** [comment]
works, thanks.
