### ISSUE TITLE
 changing the "pref" image --> image record not loaded

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#349]
this is for work records with MORE THAN ONE image record relation:

when the pref setting for the image record in relation set is changed, the complete image record section won't load anymore, but stay blank.

However: when it is changed back, everything appears as normal.

To reproduce:
change pref image in work record's relation set, save relationSet, reload page, open image tab --> it's empty
change pref image back to initial image relation, save again, reload page --> previous state recovered

**Comment by zwobit** [comment]
Seems to work on ws2 without further changes, could you also retest? Thanks.

**Comment by jodevelops** [comment]
it does work, thanks
