### ISSUE TITLE
Parsing names from VIAF

### ISSUE THREAD

**Issue by SimonGruening** [exc-asia-and-europe/ziziphus#366]
Some institutions seem to have two separate tags for their names. This seems to be the case when they're national institutions, in the current incident it is the national archives. When searching for "national archives" the results list in Ziziphus only offers nation names and you have to hover over the i-button to get the full information.
![image](https://cloud.githubusercontent.com/assets/3437957/11422247/bf3b62ba-943a-11e5-8f73-9890a4ea5c20.png)

For the "United States. National Archives and Records Administration" [VIAF-ID: #265208613] the xml looks like this:
![image](https://cloud.githubusercontent.com/assets/3437957/11422278/f38faaf8-943a-11e5-80f0-6e5d82e3de14.png)
So there are two separate tags - one for the nation and one for the institution's name.

Is it in any way possible to get both these tags shown in the results list in Ziziphus?

**Comment by zwobit** [comment]
Display Names is "United States, National Archives and Records Administration" now.

This is because of Name entries for persons which have the surname in "a" and forename in "b".

```
<ns2:subfield code="a">Bakounin</ns2:subfield>
<ns2:subfield code="b">Mikhaĭl Aleksandrovitch</ns2:subfield>
```

**Comment by SimonGruening** [comment]
Thank you! :)

**Comment by zwobit** [comment]
Close?
