### ISSUE TITLE
loading of subjects list "failed"

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#368]
in this record here:

http://kjc-ws2.kjc.uni-heidelberg.de:8650/exist/apps/ziziphus/record.xql?id=w_baaa81e1-460a-47a2-b288-7a12ed591e82&workdir=/db/data/users/johannes.alisch%40ad.uni-heidelberg.de/MyNewFolder/&imagepath=/db/data/users/johannes.alisch%40ad.uni-heidelberg.de/MyNewFolder/VRA_images/i_e7d6cce7-1114-4389-b1df-188e6a5a9866.xml

loading of the subjects failed after entering the second subject

![30-11-2015 16-10-51](https://cloud.githubusercontent.com/assets/3493493/11475345/44d4b5da-977d-11e5-9412-e131ed563b70.png)

maybe related to 
#365 

or due to session logout: 
I was told that the session expired after hitting "Save subjectSet")

**Comment by zwobit** [comment]
was fiddling around on the service instance, please retest.

**Comment by jodevelops** [comment]
sometimes it does work, sometimes it does not, please see below:

![01-12-2015 14-48-49](https://cloud.githubusercontent.com/assets/3493493/11502415/02004e22-983b-11e5-88f9-549ca4d50d6e.png)

exact search
![01-12-2015 14-49-01](https://cloud.githubusercontent.com/assets/3493493/11502417/03e5d464-983b-11e5-8d09-d70a2ffc3ba4.png)

for direct VIAF id eintry:
![01-12-2015 15-00-03](https://cloud.githubusercontent.com/assets/3493493/11502651/5f95bbfc-983c-11e5-9022-331b446245ba.png)

**Comment by zwobit** [comment]
Nice catch. Thx! Should be fixed.

**Comment by jodevelops** [comment]
looks fine!
