### ISSUE TITLE
[vocabs] missing i-icon / missing terms

### ISSUE THREAD

**Issue by SimonGruening** [exc-asia-and-europe/ziziphus#379]
The issue occured in the SubjectSet but I assume it is probably applicable to all other sets which use controlled vocabularies.

For the AAT term "power" [ID: 300374809] the info icon is missing. Looking at the xml of the term no `<relatedTerm>` tag appears in the code.

![image](https://cloud.githubusercontent.com/assets/3437957/12821820/6b831926-cb65-11e5-862e-ab4338ffdbd5.png)

```
<term id="300374809" type="subjects" value="power" authority="aat" source="getty" sources="getty" icon="getty">
<descriptiveNote value="The property of strength, influence, and dominance over others, which can be personal, political, or national. " languages="English"/>
</term>
```

```
<term id="300266439" type="subjects" value="power drills" authority="aat" source="getty" sources="getty" icon="getty">
<descriptiveNote value="Power tools used for boring holes or setting screws. Generally used for hand-held tools that are operated electrically via alternating or direct current, this term may also be extended to large machinery used to dig tunnels for mining or transportation purposes." languages="English"/>
<relatedTerm value="power drill" authority="aat" qualifiers="" languages=""/>
</term>
```

For every term from a controlled vocabulary the i-icon should appear no matter whether there is a note, related terms or a hierachy. [For the implementation of the shortened hierachy in the mouse over see #214.]

We assuem that this may also be a problem due to using an old, local xml of the Getty Vocabularies and maybe an update or a live integration would help.

Also some terms which are available on the Getty website are not yet available in Ziziphus. e.g. "human figures" [AAT #300404114] or "laurel wreath" [AAT #300400705], for others the preferred term has changed. An update or live integration of the vocabularies would hence be usefull.

**Comment by SimonGruening** [comment]
Hi Toby,
läuft das jetzt schon über die direkte Anbindung an AAT oder ist das noch das lokale AAT?

**Comment by SimonGruening** [comment]
Seems to still happen:
![image](https://cloud.githubusercontent.com/assets/3437957/13144716/905675e4-d64c-11e5-9b05-f448615cf39a.png)

**Comment by zwobit** [comment]
mmh seems to work for me on ws2 with "damn". Could you clear your caches an retry?

**Comment by zwobit** [comment]
Still uses the "local" aat files.

**Comment by SimonGruening** [comment]
Nope. Still happening:
![image](https://cloud.githubusercontent.com/assets/3437957/13426935/1332d044-dfb1-11e5-9a5b-466379b8cd69.png)
