### ISSUE TITLE
Session logout

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ziziphus#50]
If a session times out, the user should be asked to continue the session or end it. 

Currently, the session just ends without any notification or confirmation dialog, which may lead to data loss.

**Comment by zwobit** [comment]
added "tamboti" mechanism

**Comment by jodevelops** [comment]
tamboti mechanism now is "8 hours" until session logout without further notice according to CT

**Comment by zwobit** [comment]
checked. should be the same in ziziphus.

**Comment by jodevelops** [comment]
for 0.51 on ws2?
